### ISSUE TITLE
error while installing

### ISSUE THREAD

**Issue by Anna4142** [SchwarzNeuroconLab/DeepLabStream#78]
Cannot complete installation

problem with installing meta data fro package scipy==1.4.1

![image](https://user-images.githubusercontent.com/103633351/168061959-8007d666-e605-4871-b9de-da63b3c02223.png)

**Comment by JensBlack** [comment]
Hi Anna4142,

thank you for trying out DLStream. I am sorry that you ran into some errors during installation. 
If you have been able to solve them in the meantime, it would be great if you could share them here for future reference.

It would us if you could provide some minimal information on your case, like if you are using windows/Linux/mac. 
It also looks like you have not created a new environment for DLStream but are installing everything under "base". I highly recommend installing DLStream into its own environment to avoid version conflicts and issues with other installed packages.

We never ran into this issue before, but I can suggest you some workarounds:

Have you tried installing the package separately (preferably in a isolated environment) to see whether this is a problem raised by the specific package?

You could also try to change the version number in the requirements.txt (e.g. removing it completely) and see whether a newer version of scipy is working for you.

Otherwise, as this is a problem with scipy, their own documentation should give you some advice on how to handle this issue.

Please let me know if it worked for you and open the issue again if necessary.

best,
Jens
