### ISSUE TITLE
Intel realsense camera set up error

### ISSUE THREAD

**Issue by tjoy20** [SchwarzNeuroconLab/DeepLabStream#89]
Hi - thank you for developing and sharing DeepLabStream. I'm starting to work with this - I get this error when I try to stream with the gui and also when running DeepLabStream.py. It detects the camera (only 1 installed) but is unable to stream - error msg attached (I'm running this on windows). Would be great if I could get some help with this -thank you
![Capture](https://user-images.githubusercontent.com/69219166/182473743-14d33c56-595d-4054-9ff0-370fd6f706a0.PNG)

**Comment by JensBlack** [comment]
Hi tjoy20,

thank you for installing DLStream and welcome to the community! If you want some quick answers, we also have a slack channel that you can join where fellow users might be able to help.

It looks like your camera was not properly engaged, can you send me your settings.ini file (or post a screenshot) so that I can get a better understanding of your setup?

Make sure that the IntelRealSense camera is connected to your computer via USB3 (not 2) and that it works (check with their own manager). However, the manager cannot run while DLStream is engaging the camera as it is blocking any other software from using the camera. 

Have you verified that it works with a different camera? Any webcam will work. Although unlikely, your settings might have mislead DLStream in assuming some configuration you didn't intend.

Please let me know.

Best,
Jens

**Comment by tjoy20** [comment]
Hi Jens,
Thanks for the response. Will join the slack group.
The camera is connected to USB3 and I also tested this with its own camera manager - I am able record and save and use all of its functions- depth , adjust framerate, exposure so on. I haven't tried another camera yet. Here's a snapshot of the settings.ini
![snapshot of settings ini](https://user-images.githubusercontent.com/69219166/184239429-1d15efe4-d3db-4534-b05f-e79adc0a7e27.PNG)
 
Thanks,
Teena

**Comment by JensBlack** [comment]
From your settings, I can see that you are using a non-standard resolution and framerate, is that intended? Have you tried with a standard resolutionand framerate? 

Another question is what type of Intel Realsense are you using? Is it the same we used in the paper? It might be that you have a camera that needs additional parameters to run successfully in DLStream. Unfortunately the IntelRealSense SDK is not very straight forward in documentation.

Here are some references to their own GitHub Issues. It seems to be a common issue with some cameras.

https://github.com/IntelRealSense/librealsense/issues/2818

https://github.com/IntelRealSense/librealsense/issues?q=is%3Aissue+runtime+error+pipeline.start

Please let me and other users know if you found a solution. Sometimes unplugging and replugging seem to work.

**Comment by JensBlack** [comment]
I will close the issue for now as it seems to be an issue with the camera itself. Please feel free to open it again.
